[package]
name = "thelema_render"
version = "0.1.0"
edition = "2021"
default-run = "thelema_render"

[dependencies]
glam = "0.27.0"
sefirot = { path = "../sefirot/sefirot", features = ["glam"] }
sefirot_testbed = { path = "../sefirot/testbed" }
tiff = "0.9.1"
