[package]
name = "thelema_render"
version = "0.1.0"
edition = "2021"
default-run = "thelema_render"

[dependencies]
glam = "0.27.0"
image = "0.25.2"
sefirot = { path = "../sefirot/sefirot", features = ["debug", "trace", "glam"] }
sefirot_testbed = { path = "../sefirot/testbed", features = ["video"] }
