[package]
name = "thelema_render"
version = "0.1.0"
edition = "2021"
default-run = "thelema_render"

[dependencies]
sefirot = { path = "../sefirot/sefirot", features = ["debug", "trace"] }
sefirot_testbed = { path = "../sefirot/testbed" }
